# $Id: Makefile,v 1.1 2003/09/17 14:37:55 zigg Exp $

include ../GLOBAL/global.mk

PACKAGE_NAME =		tora
PACKAGE_VERSION =	1.3.11

DIST_FILES =		${PACKAGE_NAME}-alpha-${PACKAGE_VERSION}.tar.gz

PACKAGE_DESCRIPTION =	Toolkit for Oracle
PACKAGE_CATEGORY =	application

CONFIGURE_ARGS =	--prefix='${FAKE_DEST_VAR}${INSTALL_PREFIX}' \
			--enable-opt-flag='${CFLAGS}'

MAKE_PROGRAM =		gmake

BUILD_MAKE_ARGS =	
BUILD_MAKE_ENV =	

