# $Id: Makefile,v 1.1 2002/11/30 19:57:10 zigg Exp $

include ../GLOBAL/global.mk

PACKAGE_NAME =		fetchmail
PACKAGE_VERSION =	6.1.2

PACKAGE_DESCRIPTION =	fetchmail
PACKAGE_CATEGORY =	utility

CONFIGURE_ARGS +=	--disable-nls
FAKE_DEST_VAR =

