#!/bin/sh
#
#  $Id: init_d_openssh,v 1.2 2003/09/18 15:06:40 zigg Exp $
#
#  Start/stop script for OpenSSH
#

case "$1" in
'start')
	kill `cat /etc/ssh/sshd.pid`
        if [ -f /usr/sbin/sshd ] ; then
                /usr/sbin/sshd
	else
		echo $0: could not find sshd >&2
		exit 1
        fi
        ;;
'stop')
	kill `cat /etc/ssh/sshd.pid`
        ;;
*)
        echo $0: usage: /etc/init.d/openssh { start | stop } >&2
        exit 1
        ;;
esac

