#!/bin/sh
#
#  $Id: postinstall,v 1.4 2002/11/30 19:16:12 zigg Exp $
#
#  Relocate configuration files, install sample configs, generate keys,
#  setup privsep prerequisites, and start OpenSSH
#

for f in ssh_config ssh_host_dsa_key ssh_host_dsa_key.pub ssh_host_key \
	 ssh_host_key.pub ssh_host_rsa_key ssh_host_rsa_key.pub \
	 sshd_config
do
	if [ -f /etc/$f ]
	then
		mv /etc/$f /etc/ssh/$f
	fi
done

for f in ssh_config sshd_config
do
	if [ ! -f /etc/ssh/$f ]
	then
		cp -p /usr/share/examples/openssh/$f /etc/ssh/
	fi
done

if [ -f /etc/ssh/ssh_host_key ]
then
        echo 'rsa1 key already exists; skipping key generation' >&2
else
        /usr/bin/ssh-keygen -t rsa1 -f /etc/ssh/ssh_host_key -N ''
fi

if [ -f /etc/ssh/ssh_host_dsa_key ]
then
        echo 'dsa key already exists; skipping key generation' >&2
else
        /usr/bin/ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key -N ''
fi

if [ -f /etc/ssh/ssh_host_rsa_key ]
then
        echo 'rsa key already exists; skipping key generation' >&2
else
        /usr/bin/ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -N ''
fi

if /usr/bin/id sshd
then
	echo 'sshd user already exists; not adding' >&2
else
	/usr/sbin/groupadd sshd
	/usr/sbin/useradd -d /var/empty -g sshd sshd
fi

/etc/init.d/openssh start

