# $Id: Makefile,v 1.3 2002/07/15 13:47:09 zigg Exp $

include ../GLOBAL/global.mk

PACKAGE_NAME =		blackbx
PACKAGE_VERSION =	0.65.0beta2

PACKAGE_SOURCE_NAME =	blackbox-${PACKAGE_VERSION}

PACKAGE_DESCRIPTION =	Blackbox Window Manager
PACKAGE_VENDOR =	Blackbox development team
PACKAGE_CATEGORY =	application

FAKE_DEST_VAR =

