# $Id: Makefile,v 1.2 2002/07/08 17:20:00 zigg Exp $

include ../GLOBAL/global.mk

PACKAGE_NAME =		blackbx
PACKAGE_VERSION =	0.65.0beta1

PACKAGE_SOURCE_NAME =	blackbox-${PACKAGE_VERSION}

PACKAGE_DESCRIPTION =	Blackbox Window Manager
PACKAGE_VENDOR =	Blackbox development team
PACKAGE_CATEGORY =	application

FAKE_DEST_VAR =

