# $Id: Makefile,v 1.1 2002/07/05 13:59:51 zigg Exp $

include ../GLOBAL/global.mk

PACKAGE_NAME =		blackbx
PACKAGE_VERSION =	0.62.1

PACKAGE_SOURCE_NAME =	blackbox-${PACKAGE_VERSION}

PACKAGE_DESCRIPTION =	Blackbox Window Manager
PACKAGE_VENDOR =	Blackbox development team
PACKAGE_CATEGORY =	application

FAKE_DEST_VAR =

