# $Id: Makefile,v 1.1 2002/11/05 12:35:18 zigg Exp $

include ../GLOBAL/global.mk

PACKAGE_NAME =		x2vnc
PACKAGE_VERSION =	1.4

PACKAGE_DESCRIPTION =	x2vnc
PACKAGE_CATEGORY =	utility

BUILD_MAKE_ARGS =

pre-fake:
	mkdir -p ${FAKE_DIRECTORY}${INSTALL_PREFIX}/bin
	mkdir -p ${FAKE_DIRECTORY}${INSTALL_MANDIR}/man1

