# $Id: Makefile,v 1.1 2002/07/08 17:17:41 zigg Exp $

include ../GLOBAL/global.mk

PACKAGE_NAME =		fluxbox
PACKAGE_VERSION =	0.1.9

PACKAGE_SOURCE_NAME =	fluxbox-${PACKAGE_VERSION}

PACKAGE_DESCRIPTION =	Fluxbox Window Manager
PACKAGE_VENDOR =	Fluxbox development team
PACKAGE_CATEGORY =	application

CONFIGURE_ARGS +=	--enable-ordered-pseudo
FAKE_DEST_VAR =

