# $Id: Makefile,v 1.1 2002/01/21 13:45:57 zigg Exp $

include ../GLOBAL/global.mk

PACKAGE_NAME =		mktemp
PACKAGE_VERSION =	1.4

PACKAGE_DESCRIPTION =	mktemp
PACKAGE_VENDOR =	Todd Miller
PACKAGE_CATEGORY =	utility

DIST_FILES =		${PACKAGE_NAME}-${PACKAGE_VERSION}.tar.gz

#CONFIGURE_ARGS +=	--without-gssapi
#FAKE_PREFIX_FLAG =	--prefix=/usr

