# $Id: Makefile,v 1.2 2002/02/07 20:38:24 zigg Exp $

include ../GLOBAL/global.mk

PACKAGE_NAME =		mktemp
PACKAGE_VERSION =	1.4

PACKAGE_DESCRIPTION =	mktemp
PACKAGE_VENDOR =	Todd Miller
PACKAGE_CATEGORY =	utility

DIST_FILES =		${PACKAGE_NAME}-${PACKAGE_VERSION}.tar.gz

