# $Id: Makefile,v 1.1 2003/09/17 14:39:44 zigg Exp $

include ../GLOBAL/global.mk

PACKAGE_NAME =		procmail
PACKAGE_VERSION =	3.22

PACKAGE_DESCRIPTION =	procmail
PACKAGE_CATEGORY =	application

CONFIGURE_TARGET =	override-configure

BUILD_MAKE_ENV =	OPT="${CFLAGS}"

FAKE_MAKE_TARGET =	install install-suid

override-configure:

