# $Id: Makefile,v 1.1 2003/09/17 14:35:51 zigg Exp $

include ../GLOBAL/global.mk

PACKAGE_NAME =		enscript
PACKAGE_VERSION =	1.6.4

PACKAGE_DESCRIPTION =	GNU enscript
PACKAGE_CATEGORY =	utility

FAKE_DEST_VAR =

