# $Id: Makefile,v 1.1 2002/11/30 19:42:09 zigg Exp $

include ../GLOBAL/global.mk

PACKAGE_NAME =		flex
PACKAGE_VERSION =	2.5.4a

PACKAGE_SOURCE_NAME =	${PACKAGE_NAME}-2.5.4
DIST_FILES =		${PACKAGE_SOURCE_NAME}a.tar.gz

CONFIGURE_ARGS =	--prefix='${FAKE_DEST_VAR}${INSTALL_PREFIX}'

PACKAGE_DESCRIPTION =	Fast lexical analyzer generator
PACKAGE_CATEGORY =	application

