# $Id: Makefile,v 1.1 2002/10/31 13:47:56 zigg Exp $

include ../GLOBAL/global.mk

PACKAGE_NAME =		gmake
PACKAGE_VERSION =	3.80
PACKAGE_SOURCE_NAME =	make-${PACKAGE_VERSION}

PACKAGE_DESCRIPTION =	GNU make
PACKAGE_CATEGORY =	utility

CONFIGURE_ARGS +=	--program-prefix=g
FAKE_DEST_VAR =

