# $Id: Makefile,v 1.5 2003/02/07 14:26:03 zigg Exp $

include ../GLOBAL/global.mk

PACKAGE_NAME =		cvs
PACKAGE_VERSION =	1.11.5

PACKAGE_DESCRIPTION =	Concurrent Versions System
PACKAGE_CATEGORY =	utility

CONFIGURE_ARGS +=	--without-gssapi
FAKE_DEST_VAR =

