# $Id: Makefile,v 1.7 2004/08/13 17:45:20 zigg Exp $

include ../GLOBAL/global.mk

PACKAGE_NAME =		cvs
PACKAGE_VERSION =	1.11.17

PACKAGE_DESCRIPTION =	Concurrent Versions System
PACKAGE_CATEGORY =	utility

CONFIGURE_ARGS +=	--without-gssapi
FAKE_DEST_VAR =

