# $Id: Makefile,v 1.6 2003/09/17 14:30:42 zigg Exp $

include ../GLOBAL/global.mk

PACKAGE_NAME =		cvs
PACKAGE_VERSION =	1.11.6

PACKAGE_DESCRIPTION =	Concurrent Versions System
PACKAGE_CATEGORY =	utility

CONFIGURE_ARGS +=	--without-gssapi
FAKE_DEST_VAR =

