# $Id: Makefile,v 1.1 2002/07/22 16:57:45 zigg Exp $

include ../GLOBAL/global.mk

PACKAGE_NAME =		gnupg
PACKAGE_VERSION =	1.0.7

PACKAGE_DESCRIPTION =	GNU Privacy Guard
PACKAGE_VENDOR =	Free Software Foundation
PACKAGE_CATEGORY =	application

FAKE_DEST_VAR =

