# $Id: Makefile,v 1.1 2003/02/04 13:00:59 zigg Exp $

include ../GLOBAL/global.mk

PACKAGE_NAME =		hpijs
PACKAGE_VERSION =	1.3

PACKAGE_DESCRIPTION =	Hewlett-Packard Inkjet Driver System
PACKAGE_CATEGORY =	system

BUILD_MAKE_ARGS =	CC="gcc"
BUILD_MAKE_ENV =	CC="gcc"
FAKE_DEST_VAR =

