# $Id: Makefile,v 1.1 2002/07/15 12:06:40 zigg Exp $

include ../GLOBAL/global.mk

PACKAGE_NAME =		gtar
PACKAGE_VERSION =	1.13

PACKAGE_SOURCE_NAME =	tar-${PACKAGE_VERSION}

PACKAGE_DESCRIPTION =	GNU tar
PACKAGE_VENDOR =	Free Software Foundation
PACKAGE_CATEGORY =	utility

CONFIGURE_ARGS +=	--program-prefix=g --disable-nls
FAKE_DEST_VAR =

