# $Id: Makefile,v 1.1 2002/07/15 15:18:25 zigg Exp $

include ../GLOBAL/global.mk

PACKAGE_NAME =		bbkeys
PACKAGE_VERSION =	0.8.4

PACKAGE_DESCRIPTION =	Blackbox keygrabber
PACKAGE_VENDOR =	Blackbox development team
PACKAGE_CATEGORY =	utility

FAKE_DEST_VAR =

