# $Id: Makefile,v 1.1 2002/10/31 18:38:44 zigg Exp $

include ../GLOBAL/global.mk

PACKAGE_NAME =		sudo
PACKAGE_VERSION =	1.6.6

PACKAGE_DESCRIPTION =	Sudo
PACKAGE_CATEGORY =	utility

FAKE_DEST_VAR =

post-fake:
	cd ${FAKE_DIRECTORY}/etc && mv sudoers sudoers.example


