# $Id: Makefile,v 1.2 2003/09/17 14:26:51 zigg Exp $

include ../GLOBAL/global.mk

PACKAGE_NAME =		sudo
PACKAGE_VERSION =	1.6.7p5

PACKAGE_DESCRIPTION =	Sudo
PACKAGE_CATEGORY =	utility

FAKE_DEST_VAR =

post-fake:
	cd ${FAKE_DIRECTORY}/etc && mv sudoers sudoers.example


